export const base = {
  sizes: {
    borderRadius: '0.5rem',
    formControl: '2rem',
    fonts: {
      xxs: '0.625rem',
      xs: '0.75rem',
      sm: '0.875rem',
      md: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      xxl: '1.5rem',
      xxxl: '2rem',
    },
  },
  fonts: {
    body: "'Figtree', sans-serif",
    title: "'Lora', serif",
  },
  zIndicies: {
    loadingOverlay: 9000,
    dropdownMenu: 8000,
    dialog: 7000,
  },
  shadows: {
    default: 'none',
    card: 'none',
  },
  colors: {
    error: '#E74C3C',
    errorHover: '#C0392B',
    errorForeground: '#ffffff',
    success: '#27AE60',
    successHover: '#1E8449',
    warning: '#F1C40F',
    warningHover: '#D4AC0D',
    info: '#3498DB',
    infoHover: '#2E86C1',
    anchorColor: '#0070f3',
    anchorColorHover: '#0366d6',
    grayDarker: '#6c757d',
    gray: '#c0c3c6',
    grayLighter: '#e3e3e3',
  },
};
